### ISSUE TITLE
Database of Events

### ISSUE THREAD

**Issue by rufuspollock** [rgrp/climate-negotiations#14]
Create a database of events as CSV document in `/data/events.csv`

Imagine this can come directly from: https://github.com/medialab/climateDebateExplorer/blob/master/ENB-data/metadata_overview/events_metadata.json

Fields:

```
id:       # id - do not mind this being meaningful e.g. durban-2012 or something rather 001 but up to you
title:    # e.g. Durban Climate Change Conference - COP17/CMP7 
country:
city:     # e.g. Durban  - question do we need country and city separate - we could combine into place ??
date:
year:   # 2012
```

Note:
- could add a date which was an actual date or even separate start, end.

**Comment by pauloborges** [comment]
Pushed a commit with the database, check [this file](https://github.com/rgrp/climate-negotiations/blob/master/data/events.csv).

The current `id` schema is as following: `city-yearX`, where `X` is a character ranging from `a` if there're repeated ids without it.

The `csv` file is sorted by year and id.

**Comment by rufuspollock** [comment]
FIXED.
